Azeem Enterprises/azeem/core/urls.py
from xml.dom.minidom import Document
from django.urls import path
from core.views import SignUpView, ProfileView
from core import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path("contact",views.contact, name='contact'),
    path('startcontract', views.UploadFile, name='startcontract'),
    path("showcontact",views.show_contact, name='showcontact'),
    path("showcontract",views.show_contract, name='showcontract'),
    path("pin",views.pin, name='pin'),
    path("employee",views.employee, name='employee'),
    path("dashboard",views.dashboard, name='dashboard'),
    path("order_history",views.order_history, name='order_history'),
    path("tourism",views.tourism, name='tourism'),
    path("show_tourism",views.show_tourism, name='show_tourism'),
    path("tourism_page",views.tourism_page, name='tourism_page'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Azeem Enterprises/azeem/django_user/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.views.generic import TemplateView

from core import urls 

urlpatterns = [
    path('azeem/', admin.site.urls),

    path('', include('core.urls')),

    # Login and Logout
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='commons/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),

    # Main Page 
    path('', TemplateView.as_view(template_name='home.html'), name='home'), 

    # Change Password
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='commons/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='commons/password-reset/password_reset.html',
             subject_template_name='commons/password-reset/password_reset_subject.txt',
             email_template_name='commons/password-reset/password_reset_email.html',
             success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='commons/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

Azeem Enterprises/azeem/core/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class StratContract1(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=120)
    file = models.FileField(blank=True, null=True,upload_to='documents/',default=False)
    desc=models.TextField()
    price=models.FloatField()
    phone=models.CharField(max_length=100)

   
    def __str__(self):
        return self.name

class Contact(models.Model):
    #user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField( max_length=120)
    email=models.EmailField(max_length=120)
    phone=models.CharField(max_length=120)
    desc=models.TextField()
    date=models.DateField()

    def __str__(self):
        return self.name



class Employee(models.Model):
    #user=models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=120)
    designation=models.CharField(max_length=100)
    phone=models.CharField( max_length=50)
    address=models.CharField(max_length=200)

    def __str__(self):
        return self.name
     
class Route_From(models.Model):
    route_from=models.CharField(max_length=100)

    def __str__(self):
        return self.route_from

class Route_To(models.Model):
    route_to=models.CharField(max_length=100)

    def __str__(self):
        return self.route_to





class Tourism(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    expected_rate=models.FloatField()
    route_from=models.ForeignKey(Route_From,on_delete=models.CASCADE)
    route_to=models.ForeignKey(Route_To,on_delete=models.CASCADE)


    def __str__(self):
        return self.title

class Tourism_Apply_Form(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=120)
    phone=models.CharField( max_length=50)
    travel_date=models.CharField(max_length=40)
    persons = models.CharField(max_length=120)
    from_route=models.ForeignKey(Route_From,on_delete=models.CASCADE)
    to_route=models.ForeignKey(Route_To,on_delete=models.CASCADE)
    adult=models.CharField(max_length=100)
    child=models.CharField(max_length=100)

    def __str__(self):
        return self.name

Azeem Enterprises/azeem/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django import forms

# Sign Up Form
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'password1', 
            'password2', 
            ]
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
            'password1':forms.TextInput(attrs={'class':'form-control'}),
            'password2':forms.TextInput(attrs={'class':'form-control'}),
        }


# Profile Form
class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name', 
            'last_name', 
            'email',
            ]

from .models import StratContract1,Tourism_Apply_Form

class StartContractForm(forms.ModelForm):
    class Meta:
        model = StratContract1
        file=forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple':True}))
        fields = ['user','name', 'email', 'file','desc','price','phone']


class Tourism_Apply_Form1(forms.ModelForm):

	class Meta:
		model = Tourism_Apply_Form
		fields = '__all__'	
    

Azeem Enterprises/azeem/templates/Tourism_apply_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
  <div>
    <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
</div>

<div class="card shadow m-5">
    <div class="card-body">
        <h5 class="p-2 text-danger " style="bordder-bottom : 2x solid orange">Contract Details:</h5>

    </div>
    <div class="container my-4">
    <form method="post" class="form-group">
        {% csrf_token %}
        <table>
          Your username is "{{user.username}}" <hr>
          Select Username :{{ form.user }}
          
          <div class="form-group my-3">
            <label for="id_name">Name:</label>
            <input type="text" name="name" class="form-control "  maxlength="100" required id="id_name">
        </div>
        <div class="form-group my-3">
          <label for="id_email">Email:</label>
          <input type="email" name="email" class="form-control is-invalid"  maxlength="120" required id="id_email">
      </div>
      <div class="form-group my-3">
        <label for="id_phone">Phone:</label>
    <input type="text" name="phone" class="form-control "  maxlength="50" required id="id_phone">
    </div>
    <div class="form-group my-3">
      <label for="id_travel_date">Travel date:</label>
      <input type="text" name="travel_date" class="form-control "  maxlength="40" required id="id_travel_date">
      
  </div>
  <div class="form-group my-3">
    <label for="id_persons">Persons:</label>
    <input type="text" name="persons" class="form-control "  maxlength="120" required id="id_persons">
</div>
<div class="form-group my-3">
  Select Route From :{{form.from_route}}
</div>
<div class="form-group my-3">
 Select Route To: {{form.to_route}}
</div>
<div class="form-group my-3">
  <label for="id_adult">Adult:</label>
  <input type="text" name="adult" class="form-control "  maxlength="100" required id="id_adult">
</div>
<div class="form-group my-3">
  <label for="id_child">Child:</label>
  <input type="text" name="child" class="form-control "  maxlength="100" required id="id_child">
</div>

          <tr>
            <td>&nbsp;</td>
            <td><input type="submit" value="Submit"></td>
          </tr>                
        </table>
      </form>
</body>
</html>

Azeem Enterprises/azeem/templates/Tourism_apply_form_details.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
<a href="{% url 'home' %}"><button type="button" class="btn btn-outline-danger my-1">Home</button></a>

<h1 class="text-center text-danger">Dashboard For Checking Booking  OF Azeem Enterprises</h1>
<div class="card-group">
    <div class="card">
      <img src="{% static 'employee.jpg' %}" class="img-thumbnail" 
        alt="Employee" />
      <div class="card-body">
        <h5 class="card-title text-danger">Employee</h5>
        <p class="card-text text-danger">
          Here Total Booking Detail is Mentioned.
        </p>
        <h3 class="text-danger">My Booings:{{a1}}</h3>
  
        
        <table class="table table-bordered ">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Contact</th>
                <th scope="col">Travel Date</th>
                <th scope="col">Persons</th>
                <th scope="col">From Route</th>
                <th scope="col">To Route</th>
                <th scope="col">Adults</th>
                <th scope="col">Childs</th>
              </tr>
            </thead>
            {% for al in all1 %}
            <tbody>
              <tr>
                <th scope="row">{{al.id}}</th>
                <td> {{al.name}} </td>
                <td>{{al.email}}</td>
                <td>{{al.phone}}</td>
                <td>{{al.travel_date}}</td>
                <td>{{al.persons}}</td>
                <td>{{al.from_route}}</td>
                <td>{{al.to_route}}</td>
                <td>{{al.adult}}</td>
                <td>{{al.child}}</td>
                
              </tr>
              
            </tbody>
            {% endfor %}
          </table>
        </p>
      </div>
    </div>

    {% endblock body %}
    
<div>
    
    </div>

Azeem Enterprises/azeem/templates/Tourism_page.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href=" {% static '/css/styles.css' %} " rel="stylesheet" />
        <link href=" {% static '/js/scripts.js' %} " rel="stylesheet" />
{% endblock title %}

{% block body %}
<div>
<img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">


<div class="d-grid gap-2 d-md-flex justify-content-md-end">
   
    <a href="{% url 'tourism' %}"><button type="button" class="btn btn-outline-danger my-1 align-right">Apply Now</button></a>
    <a href="{% url 'show_tourism' %}"><button type="button" class="btn btn-outline-danger my-1 align-right">My Bookings</button></a>
  </div>
     
  <header class="masthead bg-image "
  style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/Nature/full page/img(1).jpg');
  height: 100vh">
      
      <div class="container">
          <div class="masthead-subheading">{% for al in all1 %}
            {{al.title}}!</div>
          <div class="masthead-heading text-uppercase">{{al.description}}.</div>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Expected_Rate</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                
                <td scope="row"> {{al.expected_rate}} </td>
                
                
              </tr>
              
            </tbody>
          </table>
          

          <div class="input-group">
            <label for="route_from">Route To:</label>
              
          <select name="route_from" id="route_from">
            {% for al in all3 %}
            <option value="{{al.route_to}}">{{al.route_to}}</option>
            
            {% endfor %}
          </select>
            <span class="input-group-addon">--------</span>
            <label for="route_from">Route From:</label>
             
          <select name="route_from" id="route_from">
            {% for al in all2 %}
            <option value="{{al.route_from}}">{{al.route_from}}</option>
            
            {% endfor %}
          </select>
          


      </div>


  </header>
{% endfor %}

  
   




{% endblock body %}

Azeem Enterprises/azeem/templates/base.html
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        {% block css %} {% endblock css %}
    </head>
    <body>
        <!-- <h1>Built-In User Registeration / Authentication App</h1> -->

        {% block content %} {% endblock content %}

        {% block javascript %} {% endblock javascript %}
    </body>
</html>

Azeem Enterprises/azeem/templates/contact.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<div>
    <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
</div>
<div class="container  py-4">
    <h1 class="text-center text-danger">Enter Your Query And Reason To Contact Us:</h1>
    <div class="card shadow m-5">
        <div class="card-body">
            <h5 class="p-2 text-danger " style="bordder-bottom : 2x solid orange">Contact Form:</h5>
    
        </div>
    </div>
    <form method="post" action="">
    {% csrf_token %}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control "  id="name" name="name" placeholder="Enter your Name">
        </div>

        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control   " id="email" name="email" placeholder="Enter Your Email">
        </div>
        
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="phone" class="form-control   " id="phone" name="phone" placeholder="Enter Your Phone Number">
        </div>      
        
        <div class="form-group">
            <label for="desc">Reason To Contact Us...</label>
            <textarea class="form-control   " id="desc" rows="3" name="desc"></textarea>
        </div>
        
        <div class="col-md-12 text-center text-danger">
            <button type="submit" class="btn btn-outline-danger my-4 text-center">Contact</button>
            <a href="{% url 'home' %}"><button type="button" class="btn btn-outline-danger my-4">Home</button></a>
        </div>
    </form>
    
</div>
{% endblock body %}

Azeem Enterprises/azeem/templates/dashboard.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
<a href="{% url 'home' %}"><button type="button" class="btn btn-outline-danger my-1">Home</button></a>

<h1 class="text-center text-danger">Dashboard For Employee's OF Azeem Enterprises</h1>
<div class="card-group">
    <div class="card">
      <img src="{% static 'employee.jpg' %}" class="img-thumbnail" 
        alt="Employee" />
      <div class="card-body">
        <h5 class="card-title text-danger">Employee</h5>
        <p class="card-text text-danger">
          Here Total Employees Detail is Mentioned.
        </p>
        <h3 class="text-danger">Total Employees:{{a1}}</h3>
        <a href="{% url 'employee' %}"><button type="button" class="btn btn-outline-danger">Show Employees</button></a>
        <p class="card-text">
          <small class="text-muted">Last visit 1 mins ago</small>
          
        </p>
      </div>
    </div>
    <div class="card">
      <img src="{% static 'order.jpg' %}" class="img-thumbnail"
        alt="Order" />
      <div class="card-body">
        <h5 class="card-title text-danger">Contracts</h5>
        <p class="card-text text-danger">Here Total Contract Details is Mentioned.
        </p>
        <h3 class="text-danger">Total Contracts:{{a2}}</h3>
        <a href="{% url 'showcontract' %}"><button type="button" class="btn btn-outline-danger">Show Contracts</button></a>
        <p class="card-text">
          <small class="text-muted">Last visit 1 mins ago</small>
        </p>
      </div>
    </div>
    <div class="card">
      <img src="{% static 'contacto.jpg' %}" class="img-thumbnail"
        alt="contacto" />
      <div class="card-body">
        <h5 class="card-title text-danger">Contacts</h5>
        <p class="card-text text-danger">
          Here Total Contacts Details is Mentioned.
        </p>
        <h3 class="text-danger">Total Contacts:{{a3}}</h3>
        <a href="{% url 'showcontact' %}"><button type="button" class="btn btn-outline-danger">Show Contacts</button></a>
        <p class="card-text">
          <small class="text-muted">Last visit 1 mins ago</small>
        </p>
      </div>
    </div>
  </div>






{% endblock body %}

Azeem Enterprises/azeem/templates/employee.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<div>
  <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
    <h1 class="text-center text-danger my-4">Showing Details Of Employees:</h1>
<table class="table table-bordered align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>Name</th>
        <th>Designation</th>
        <th>Phone</th>
        <th>Address</th>
       
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <div class="d-flex align-items-center">
           {% for al in all %}
            <div class="ms-3">
              <p class="fw-bold mb-1">{{al.name}}</p>
              <p class="text-muted mb-0">{{al.email}}</p>
            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1">{{al.designation}}</p>
          
        </td>
        <td>
          <span class="fw-normal mb-1">{{al.phone}}</span>
        </td>
        <td>{{al.address}}</td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
  <a href="{% url 'dashboard' %}"><button type="button" class="btn btn-outline-danger my-4">Back</button></a>
{% endblock body %}

Azeem Enterprises/azeem/templates/orderhistory.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
  <div>
    <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
    <h1 class="text-center text-danger my-4">Showing Details Of My Contracts:</h1>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Contact</th>
        <th scope="col">File</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    {% for al in orders %}
    <tbody>
      <tr>
        <th scope="row">{{al.id}}</th>
        <td> {{al.name}} </td>
        <td>{{al.email}}</td>
        <td>{{al.phone}}</td>
        <td>{{al.file}}</td>
        <td>{{al.price}}</td>
        <td>{{al.desc}}</td>
      </tr>
      
    </tbody>
    {% endfor %}
  </table>
  
</body>
</html>

Azeem Enterprises/azeem/templates/pin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee's Verification</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
    <h1 class="text-center text-danger my-4">Enter Employee's Verification Pin:</h1>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group text-danger fs-3">
            <label for="name">Pin:</label>
            <input type="text" class="form-control bg-danger" id="name" name="name" placeholder="Enter Employee's Pin" >
        </div>
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-outline-danger my-4">Check Pin</button>
            </div>
</body>
</html>

Azeem Enterprises/azeem/templates/showcontact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Azeem Enterprises</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static 'public/assets/favicon.ico' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {% static '/css/styles.css' %} " rel="stylesheet" />
        <link href=" {% static '/js/scripts.js' %} " rel="stylesheet" />
    </head>

    <div>
      <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
      <h1 class="text-center text-danger my-4">Showing Details Of Contacts:</h1>
<table class="table table-bordered ">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Contact</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    {% for al in all %}
    <tbody>
      <tr>
        <th scope="row">{{al.id}}</th>
        <td> {{al.name}} </td>
        <td>{{al.email}}</td>
        <td>{{al.phone}}</td>
        <td>{{al.desc}}</td>
      </tr>
      
    </tbody>
    {% endfor %}
  </table>
  <a href="{% url 'dashboard' %}"><button type="button" class="btn btn-outline-danger my-4">Back</button></a>
</div>

Azeem Enterprises/azeem/templates/upload.html
{% load static %}
{% block title %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{% endblock title %}

{% block body %}
<div>
    <img src="{% static 'logo.png' %}" class="rounded mx-auto d-block" alt="...">
</div>

<div class="card shadow m-5">
    <div class="card-body">
        <h5 class="p-2 text-danger " style="bordder-bottom : 2x solid orange">Contract Details:</h5>

    </div>

</div>
<div class="container  py-4">
    <form method='post' class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            Your username is "{{user.username}}" <hr>
          Select Username :{{ form.user }}
        
        </div>
          
           <div class="form-group">
            <label for="id_name">Name:</label>
    <input type="text"  class="form-control " name="name" maxlength="100" required id="id_name">
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email"  class="form-control is-invalid " name="email" maxlength="120" required id="id_email">
        </div>
        <div class="form-group">
            <label for="id_file">File:</label>
    <input type="file"  class="form-control " name="file" id="id_file" multipart>
        </div>
        <div class="form-group">
            <label for="id_desc">Desc:</label>
            <textarea name="desc"  class="form-control " cols="40" rows="10" required id="id_desc">
        </textarea>
        </div>
        <div class="form-group">
            <label for="id_price">Price:</label>
            <input type="number"  class="form-control " name="price" step="any" required id="id_price">
            
        </div>
        <div class="form-group">
            <label for="id_phone">Phone:</label>
    <input type="text" name="phone"  class="form-control " maxlength="100" required id="id_phone">
            
        </div>
        
       

<div class="col-md-12 text-center text-danger">
    <button type="submit" class="btn btn-outline-danger my-4 text-center">Submit</button><br>
   
    </div>

    </form>
    {% endblock body %}

    
</html>